# Projekt Adsorptionskolonnenreaktor
Wir machen unsere erste simulation für folgendes problem:
Wir haben eine Adsorptionskolonnenreaktor welche Feuchte Luft trocknet
Hierzu wird feuchte Luft über ein "Bett" aus trockenem Absorber geleitet
Wir wollen nun simulieren wie das Wasser in den Absorber diffundiert.
Wir gehen hierzu in einfachen Teilschritten vor:

In [2]:
# initiale Situation festlegen. 
# Hierzu betrachten wir einen 2D reaktor wecher auf 100x100 zellen besteht. 
# Alle diese Zellen sind initial trocken - haben also 0 wasser. 
# Die oberste Zelle soll nun unser Wasserreservoir sein. Füllen Sie die oberste zelle mit Einsen.
import numpy as np
concentration = np.zeros([10, 10])
concentration[0,:] = np.ones(10)
print(concentration)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [ ]:
# plotten sie den initialien zustand
# if abfragen, ob i oder j außrhalb von 0-10 sind für i+-1, j+-1
for i in range(10):
    for j in range(10):
        temp = 0
        if i-1 > 0:
            a = concentration[i-1, j]
        if i+1 >= 10:
            a = 0
        if j-1 > 0:
            b = concentration[i, j-1]
        if j+1 >= 10:
            b = 0

        temp = a+b+c+d
        concentration[i,j] = 0.25*(concentration[i-1, j])+0.25*(concentration[i+1, j])+0.25*(concentration[i, j-1])+0.25*(concentration[i, j+1])

NameError: name 'a' is not defined

In [ ]:
# schreiben Sie eine funktion welche eine 100x100 matrix aufnimmt und einen diffusionsschritt vornimmt
# diffusion geschieht hier modellweise horizontal und vertikal also für zelle z
# berechnung siehe folien!

In [ ]:
# wir führen schritte aus mit unserer oben definierten funktion