# KT5 Preparation
- pop lists
- argmax & argsort
- list in list
- e.g.: x & y gegeben: über y wurde etwas berechnet: erstelle eine Liste mit den 10 größten Varianzwerten
-> bzw. allgemein höchste Elementwerte wiedergeben (vor / nach pop list)

In [6]:
# pop lists
my_list = [1, 2, 3, 4, 5]
popped_element = my_list.pop() # without any argument, last element is popped
print(popped_element)
print(my_list)

popped_element = my_list.pop(0) # with index, element at that index is popped
print(popped_element)
print(my_list)

5
[1, 2, 3, 4]
1
[2, 3, 4]


In [7]:
# argmax & argsort
import numpy as np
arr = np.array([3, 1, 2, 5, 4])
index_of_max = np.argmax(arr)
print(index_of_max)

sorted_indices = np.argsort(arr)
print(sorted_indices)

# sorted numbers
sorted_array = arr[sorted_indices]
print(sorted_array)

3
[1 2 0 4 3]
[1 2 3 4 5]


In [8]:
# list in list
nested_list = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

# accessing elements
first_sublist = nested_list[0]
print(first_sublist)

second_element_of_second_sublist = nested_list[1][1]
print(second_element_of_second_sublist)

[1, 2, 3]
5


In [9]:
# Create a list with the 10 largest variance values
import numpy as np
arr = np.random.randint(0, 100, size=(10, 10)) # 2D array with 10x10 columns
print(arr)

# Calculate the variance of each row in the original 2D array
variances = np.var(arr, axis=1)

# Get the indices of the 10 largest variances
largest_variance_indices = np.argsort(variances)[-10:]

# Create a list with the 10 largest variance values
largest_variances = variances[largest_variance_indices]
print(largest_variances)

[[91 92 79  4 47 89  0 48 96 54]
 [65 18 76 25  0  1 54 52  4 36]
 [81 65 72 60 76 26  4 79 89 26]
 [11 91 80  4 40 58 65 34 98 30]
 [19 65 17 72 81 57 47 86 90  0]
 [72 84 34 33 79 94 94 61  8 63]
 [35 94 92 81 72 72 44 56 60 41]
 [20 39 14 67 65  9 13 95 34 35]
 [88 23 19 19 37 49 51 65 95 45]
 [72 43  7 33 55 11 75 26 40 20]]
[ 394.61  502.56  653.29  692.69  719.89  746.36  746.76  905.84  955.49
 1156.8 ]


In [10]:
import numpy as np

x = np.random.randint(100)
y = np.random.randint(0, 100, size=(100, 100))  # Assuming y is a 2D 100x100 array

# Calculate variance for each column in y
variances = np.var(y, axis=0)

# Get indices of the 10 largest variances
largest_variance_indices = np.argsort(variances)[-10:]

# Create a list with the 10 largest variance values
largest_variances = variances[largest_variance_indices]
print(largest_variances)

[ 942.6731  945.3651  951.8476  954.2579  956.1784  959.88    972.7364
  976.6819  985.0024 1007.0539]
