# KT5 Preparation
- pop lists
- argmax & argsort
- list in list
- e.g.: x & y gegeben: über y wurde etwas berechnet: erstelle eine Liste mit den 10 größten Varianzwerten

In [195]:
# pop lists
my_list = [1, 2, 3, 4, 5]
popped_element = my_list.pop() # without any argument, last element is popped
print(popped_element)
print(my_list)

popped_element = my_list.pop(0) # with index, element at that index is popped
print(popped_element)
print(my_list)

5
[1, 2, 3, 4]
1
[2, 3, 4]


In [196]:
# argmax & argsort
import numpy as np
arr = np.array([3, 1, 2, 5, 4])
index_of_max = np.argmax(arr)
print(index_of_max)

sorted_indices = np.argsort(arr)
print(sorted)

# sorted numbers
sorted_array = arr[sorted_indices]
print(sorted_array)

3
[1 2 0 4 3]
[1 2 3 4 5]


In [197]:
# list in list
nested_list = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

# accessing elements
first_sublist = nested_list[0]
print(first_sublist)

second_element_of_second_sublist = nested_list[1][1]
print(second_element_of_second_sublist)

[1, 2, 3]
5


In [198]:
# Create a list with the 10 largest variance values
import numpy as np
arr = np.random.randint(0, 100, size=(10, 10)) # 2D array with 10x10 columns
print(arr)

# Calculate the variance of each row in the original 2D array
variances = np.var(arr, axis=1)

# Get the indices of the 10 largest variances
largest_variance_indices = np.argsort(variances)[-10:]

# Create a list with the 10 largest variance values
largest_variances = variances[largest_variance_indices]
print(largest_variances)

[[62 21 25 27 84 48 70 80 83 48]
 [19 85 91 62 60 48 70  0 95 12]
 [93 86 50 55 82 61 31 29 28 48]
 [44 92 29 15 39 18 17  0 77 46]
 [65 91 93 37 50 62  3  0  7 28]
 [54  2 31  9 73 82 33 96 86 54]
 [91 31 49  6 92  7 64 56 66 87]
 [86 58 71 53 66 50 96 91  7 33]
 [34 95 87 77 31 45 15 67 36 53]
 [84 13 94 54 47 81  6 73  6 32]]
[ 520.81  546.16  632.4   676.89  743.21  920.89  959.2  1016.2  1030.76
 1070.04]
