# KT5 Preparation
- pop lists
- argmax & argsort
- list in list
- e.g.: x & y gegeben: über y wurde etwas berechnet: erstelle eine Liste mit den 10 größten Varianzwerten

In [12]:
# pop lists
my_list = [1, 2, 3, 4, 5]
popped_element = my_list.pop() # without any argument, last element is popped
print(popped_element)
print(my_list)

popped_element = my_list.pop(0) # with index, element at that index is popped
print(popped_element)
print(my_list)

5
[1, 2, 3, 4]
1
[2, 3, 4]


In [13]:
# argmax & argsort
import numpy as np
arr = np.array([3, 1, 2, 5, 4])
index_of_max = np.argmax(arr)
print(index_of_max)

sorted_indices = np.argsort(arr)
print(sorted)

# sorted numbers
sorted_array = arr[sorted_indices]
print(sorted_array)

3
<built-in function sorted>
[1 2 3 4 5]


In [14]:
# list in list
nested_list = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

# accessing elements
first_sublist = nested_list[0]
print(first_sublist)

second_element_of_second_sublist = nested_list[1][1]
print(second_element_of_second_sublist)

[1, 2, 3]
5


In [15]:
# Create a list with the 10 largest variance values
import numpy as np
arr = np.random.randint(0, 100, size=(10, 10)) # 2D array with 10x10 columns
print(arr)

# Calculate the variance of each row in the original 2D array
variances = np.var(arr, axis=1)

# Get the indices of the 10 largest variances
largest_variance_indices = np.argsort(variances)[-10:]

# Create a list with the 10 largest variance values
largest_variances = variances[largest_variance_indices]
print(largest_variances)

[[49  6 85 54 83 22 13 67  6  0]
 [84 18 72 25 50 84 98 19 59 80]
 [75 61 91 17 52 63  2 71 16 27]
 [84 97 60 42 81  0 67 80  5  4]
 [16 69 85 85  4 41 34 98 96 17]
 [ 5 57 80  3 92 36 84 87 30 47]
 [65 20 89 14 85 67 49  1 87 63]
 [40 21  2  8 82 25  7 93 82 20]
 [59 43  4 20 50 56 47 70 26 28]
 [92 50 95 73  2 85 48 38 22 49]]
[ 371.01  789.89  805.65  848.84  923.6   982.25 1003.29 1084.   1172.65
 1228.  ]


In [16]:
import numpy as np

x = np.random.randint(100)
y = np.random.randint(0, 100, size=(100, 100))  # Assuming y is a 2D 100x100 array

# Calculate variance for each column in y
variances = np.var(y, axis=0)

# Get indices of the 10 largest variances
largest_variance_indices = np.argsort(variances)[-10:]

# Create a list with the 10 largest variance values
largest_variances = variances[largest_variance_indices]
print(largest_variances)

[ 932.9724  944.2056  952.0331  985.3051  997.2219 1006.4544 1006.99
 1008.6724 1027.3236 1057.8491]
