# KT5 Preparation
- pop lists
- argmax & argsort
- list in list
- e.g.: x & y gegeben: über y wurde etwas berechnet: erstelle eine Liste mit den 10 größten Varianzwerten
-> bzw. allgemein höchste Elementwerte wiedergeben (vor / nach pop list)

In [1]:
# pop lists
my_list = [1, 2, 3, 4, 5]
popped_element = my_list.pop() # without any argument, last element is popped
print(popped_element)
print(my_list)

popped_element = my_list.pop(0) # with index, element at that index is popped
print(popped_element)
print(my_list)

5
[1, 2, 3, 4]
1
[2, 3, 4]


In [2]:
# argmax & argsort
import numpy as np
arr = np.array([3, 1, 2, 5, 4])
index_of_max = np.argmax(arr) # analog für argmin
print(index_of_max)

sorted_indices = np.argsort(arr)
print(sorted_indices)

# sorted numbers
sorted_array = arr[sorted_indices]
print(sorted_array)

3
[1 2 0 4 3]
[1 2 3 4 5]


In [3]:
# list in list
nested_list = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

# accessing elements
first_sublist = nested_list[0]
print(first_sublist)

second_element_of_second_sublist = nested_list[1][1]
print(second_element_of_second_sublist)

[1, 2, 3]
5


In [4]:
# Create a list with the 10 largest variance values
import numpy as np
arr = np.random.randint(0, 100, size=(10, 10)) # 2D array with 10x10 columns
print(arr)

# Calculate the variance of each row in the original 2D array
variances = np.var(arr, axis=1)

# Get the indices of the 10 largest variances
largest_variance_indices = np.argsort(variances)[-10:]

# Create a list with the 10 largest variance values
largest_variances = variances[largest_variance_indices]
print(largest_variances)

[[25 60 46 56 63 50 84 70 73 95]
 [65 93 10 82 28 73 23 97 57 82]
 [86 96 77 17 61 63  4 71 23 30]
 [62 39 69 38 68 69 96 56 81 47]
 [53 34 13 36  6 89 86 58 77 36]
 [ 5 51  7  7 98 29 35 10 32 30]
 [12  9 21  3 27  6  9 77 60 50]
 [60 30 96 72 68 48 25 47 75  6]
 [38 12 20 86 74 62 45 75 49 14]
 [64  7 71 24 38 58 77 82 71 36]]
[301.45 356.76 568.16 604.24 638.85 655.01 717.64 755.76 851.2  912.76]


In [5]:
import numpy as np

x = np.random.randint(100)
y = np.random.randint(0, 100, size=(100, 100))  # Assuming y is a 2D 100x100 array

# Calculate variance for each column in y
variances = np.var(y, axis=0)

# Get indices of the 10 largest variances
largest_variance_indices = np.argsort(variances)[-10:]

# Create a list with the 10 largest variance values
largest_variances = variances[largest_variance_indices]
print(largest_variances)

[ 900.0179  901.9156  905.3579  910.5299  918.9611  925.3475  943.3251
  954.0004  990.3099 1045.6275]
