## Preparation for last KT(5)

In [22]:
import numpy as np
list1 = [1, 2, 3, 4, 5]
print(list1.pop(np.argmax(list1)))

5


In [23]:
arr = np.array([3, 1, 2, 5, 4])
print(np.argmax(arr))

3


### Beispielaufgabe

In [24]:
array2d = np.random.rand(10, 10)
variances = np.var(array2d, axis=1)

np.random.seed(0) # für Reproduzierbarkeit
top3_indices = np.argsort(variances)[-3:]
min3_indices = np.argsort(variances)[:3]

top3_variances = variances[top3_indices]
# top3_variances = variances[np.argsort(variances)[-3:]]
min3_variances = variances[min3_indices]

print(top3_variances)
print(min3_variances)

var_list = [0.03403099, 0.04685508, 0.06081199]
var_list.pop(0)

[0.10713175 0.11159059 0.12209258]
[0.047095   0.06676916 0.08248883]


0.03403099

In [25]:
my_list1 = [1, 2, 3, 4, 5]
ergebnis = my_list1[1:3]
kleinste3 = my_list1[:3]

print(kleinste3)
print(ergebnis)

np.array(my_list1)

[1, 2, 3]
[2, 3]


array([1, 2, 3, 4, 5])

In [26]:
array3d = np.random.rand(10, 10, 10)

flattened_array = array3d.flatten()
flattened_list = flattened_array.tolist()
popped_element = flattened_list.pop()

print("Popped element:", popped_element)
print("Remaining list length:", len(flattened_list))

Popped element: 0.6771411441114241
Remaining list length: 999


In [27]:
my_list = [1, 2, 3]
my_list.append([4, 5])
print(my_list)

[1, 2, 3, [4, 5]]


In [28]:
a = [1, 2, 3, 4 ,5]
array123 = np.array(a)
print(array123)

[1 2 3 4 5]
