## Preparation for last KT(5)

In [57]:
import numpy as np
list1 = [1, 2, 3, 4, 5]
print(list1.pop(np.argmax(list1)))

5


In [58]:
arr = np.array([3, 1, 2, 5, 4])
print(np.argmax(arr))

3


In [70]:
array2d = np.random.rand(10, 10)
array2d.flatten()
var1 = np.var(array2d)

np.random.seed(0)
top3_indices = np.argsort(variances)[-3:]
min3_indices = np.argsort(variances)[:3]

variances = np.var(array2d, axis=1)

top3_variances = variances[top3_indices]
# top3_variances = variances[np.argsort(variances)[-3:]]
min3_variances = variances[min3_indices]

print(top3_variances)
print(min3_variances)

[0.08448183 0.1100026  0.11588658]
[0.03403099 0.04685508 0.06081199]


In [87]:
my_list1 = [1, 2, 3, 4, 5]
ergebnis = my_list1[1:3]
kleinste3 = my_list1[:3]

print(kleinste3)
print(ergebnis)

np.array(my_list1)

[1, 2, 3]
[2, 3]


array([1, 2, 3, 4, 5])