## Aufgabe 4: Arbeiten mit mehrdimensionalen Arrays
Erstellen Sie eine 3D-Numpy-Matrix, die die Punktzahlen von Schülern in verschiedenen Klassen über mehrere Tests speichert. Jede Dimension repräsentiert:

1. Dimension: Klassen (z. B. 3 Schulklassen),
2. Dimension: Schüler in einer Schulklasse (z.B. 5 Schüler pro Klasse),
3. Dimension: Punktzahlen der Tests (z. B. 4 Tests). (Punktzahl von 0 bis 100)
Aufgaben:

a) Finden Sie die durchschnittliche Punktzahl jedes Schülers in jeder Klasse.

b) Ermitteln Sie die Gesamtklasse mit dem besten Durchschnitt über alle Tests hinweg.

c) Ermitteln Sie den Schüler mit der höchsten Einzelleistung (höchste Punktzahl über alle Tests und Klassen).

In [251]:
import numpy as np

scores = np.random.randint(0, 101, size = (3, 5, 4))

# a)
student_average = scores.mean(axis=2)
print("Durchschnittliche Punktzahl pro Schüler:\n", student_average)
# alternativ mit numpy.mean()
student_averages = np.average(scores, axis=2)
print("Durchschnittliche Punktzahl pro Schüler in jeder Klasse: \n", student_averages)

# b)
class_average = student_average.mean(axis=1)
best_class = np.argmax(class_average)
print(f"Klasse mit bestem Durchschnitt: {best_class}, Durchschnitt: {class_average[best_class]}")

# c)
max_score = 0
best_class, best_student, best_test = None, None, None

for i in range(3):
    for j in range(5):
        for k in range(4):
            if scores[i,j,k] > max_score:
                max_score = scores[i,j,k]
                best_class, best_student, best_test = [i,j,k]
print("Punktzahl-Matrix:\n", scores)
print(f"Höchste Punktzahl: {max_score}")
print(f"Position: Klasse {best_class}, Schüler {best_student}, Test{best_test}")

Durchschnittliche Punktzahl pro Schüler:
 [[55.5  48.75 42.25 44.   28.25]
 [25.75 50.75 56.75 46.75 70.  ]
 [51.75 37.75 53.25 38.5  50.75]]
Durchschnittliche Punktzahl pro Schüler in jeder Klasse: 
 [[55.5  48.75 42.25 44.   28.25]
 [25.75 50.75 56.75 46.75 70.  ]
 [51.75 37.75 53.25 38.5  50.75]]
Klasse mit bestem Durchschnitt: 1, Durchschnitt: 50.0
Punktzahl-Matrix:
 [[[32 39 81 70]
  [82 12 88 13]
  [41  7 97 24]
  [17 83 72  4]
  [22 68  7 16]]

 [[ 1 46 56  0]
  [34 26 99 44]
  [34 50 65 78]
  [ 5 60 78 44]
  [83 50 92 55]]

 [[88 42  7 70]
  [91 36 16  8]
  [64 69 14 66]
  [42 41  2 69]
  [45 97 30 31]]]
Höchste Punktzahl: 99
Position: Klasse 1, Schüler 1, Test2


## Aufgabe 5: String-Manipulation & Analyse
Sie haben eine Liste von Strings, die Studenten und ihre Punktzahlen in einem Format speichert:
"Name: <Name>, Punkte: [<Punkt1>, <Punkt2>, ...]". Verwende folgende List: 

students = [
"Name: Jürgen, Punkte: [75, 80, 85]", 
"Name: Peter, Punkte: [66, 77, 88]", 
"Name: Justus, Punkte: [68, 33, 94]"
]


Aufgaben:

a) Schreiben Sie ein Programm, das die Liste einliest und die Durchschnittspunkte jedes Studenten berechnet.

b) Finden Sie den Studenten mit der besten Gesamtleistung.

c) Geben Sie alle Ergebnisse in sortierter Reihenfolge nach Durchschnittspunkten aus.

In [252]:
students = [
"Name: Jürgen, Punkte: [75, 80, 85]", 
"Name: Peter, Punkte: [66, 77, 88]", 
"Name: Justus, Punkte: [68, 33, 94]"
]

# a)
results = []

for entry in students:
    name_part, scores_part = entry.split(", Punkte: ")
    name = name_part.split(": ")[1]
    scores = eval(scores_part)
    avg_score = sum(scores) / 3

    results.append([name, avg_score])
print(results)

# b)
best_student = None
highest_avg = 0

for result in results:
    if result[1] > highest_avg:
        highest_avg = result[1]
        best_student = result[0]

print(f"Höchster Durchschnitt: {highest_avg} des Student {best_student}.")

# c)
averages = np.array([result[1] for result in results])
sorted_indices = np.argsort(averages)
sorted_results = [results[i] for i in sorted_indices]

print("Durchschnittspunkte pro Student: ")
for name, avg in sorted_results:
    print(f"{name}: {avg}")

[['Jürgen', 80.0], ['Peter', 77.0], ['Justus', 65.0]]
Höchster Durchschnitt: 80.0 des Student Jürgen.
Durchschnittspunkte pro Student: 
Justus: 65.0
Peter: 77.0
Jürgen: 80.0


## Aufgabe 6: Zeitbasierte Simulation
Erstellen Sie eine Simulation für die Punktzahlen von Schülern, die sich über ein Jahr hinweg entwickeln. Jedes Quartal (4 Zeitpunkte) sollen sich die Punktzahlen durch einen Fortschrittsfaktor ändern. Der Fortschrittsfaktor wird zufällig generiert.

Aufgaben:

a) Erstellen Sie eine Punktzahl-Liste für 10 Schüler, die jeweils mit einem Startwert zwischen 50 und 100 beginnt.

b) Simulieren Sie die Punktzahlen über 4 Quartale, wobei in jedem Quartal ein Zufallsfaktor zwischen 1.01 (1% Zuwachs) und 1.10 (10% Zuwachs) angewendet wird.

c) Geben Sie die Endpunktzahlen der Schüler aus und ermitteln Sie denjenigen mit der besten Gesamtkurve.

In [253]:
# a)
scores = np.random.uniform(50, 101, size=10)
print("Startpunktzahlen:", scores)

# b)
for _ in range(4):
    growth_factors = np.random.uniform(1.01, 1.10, size=scores.shape)
    scores *= growth_factors

# c)
best_student = np.argmax(scores)
print("Endpunktzahlen:", scores)
print(f"Schüler mit der besten Gesamtkurve: Index {best_student}, Endpunktzahl: {scores[best_student]:.2f}")

Startpunktzahlen: [ 91.91108093  97.61621572  68.13185178  77.24814942  50.06032655
  70.15517245 100.8767438   84.36965102  58.5073378   57.6994321 ]
Endpunktzahlen: [108.21455133 126.4065505   81.54590781  98.13689773  63.5543363
  84.8880637  123.77768154  98.2624306   71.53609705  67.34008852]
Schüler mit der besten Gesamtkurve: Index 1, Endpunktzahl: 126.41


## Aufgabe 7: Kreative Klassenaufgabe, Bibliothekssystem
Stellen Sie sich vor, Sie entwickeln ein System für eine Bibliothek. Ihre Aufgabe ist es, eine Klasse Library zu erstellen, die die Bücher der Bibliothek verwaltet. Jedes Buch hat einen Titel, einen Autor und eine Verfügbarkeit (ob es ausgeliehen ist oder nicht).

Anforderungen:
Die Klasse Library soll Methoden haben, um:
Ein Buch hinzuzufügen.
Ein Buch auszuleihen.
Ein Buch zurückzugeben.
Alle verfügbaren Bücher anzuzeigen.
Wenn jemand ein Buch ausleiht, das nicht verfügbar ist, soll eine entsprechende Nachricht ausgegeben werden.
Implementieren Sie auch eine Methode, die alle Bücher eines bestimmten Autors auflistet.

In [254]:
class Library:
    def __init__(self):
        self.books = []
    
    def add_book(self, title, author):
        self.books.append({"title": title, "author": author, "available": True})
        print(f"Buch verfügbar: {title} von {author}")
    
    def borrow_book(self, title):
        for book in self.books:
            if book["available"]:
                book["available"] = False
                print(f"Du hast das Buch '{title}' ausgeliehen.")
                return
            else:
                print(f"Das Buch '{title}' ist nicht verfügbar.")
                return

    def return_book(self, title):
        for book in self.books:
            if book["title"] == title:
                if not book["available"]:
                    book["available"] = True
                    print(f"Das Buch '{title}' wurde zurückgegeben.")
                    return
                else:
                    print(f"Das Buch '{title0}' wurde nicht ausgeliehen.")
                    return

    def show_available_books(self):
        available_books = [book["title"] for book in self.books if book["available"]]
        if available_books:
            print("Verfügbare Bücher:")
            for title in available_books:
                print(f"- {title}")
        else:
            print("Kein Bücher verfügbar.")

    def show_books_by_author(self, author):
        author_books = [book["title"] for book in self.books if book["author"] == author]
        if author_books:
            print(f"Bücher von {author}:")
            for title in author_books:
                print(f"- {title}")
        else:
            print(f"Es gibt kein Bücher von diesem {author}.")
            

In [255]:
library = Library()
library.add_book("1984", "George Orwell")
library.add_book("Animal Farm", "George Orwell")
library.add_book("To Kill a Mockingbird", "Harper Lee")

library.borrow_book("1984")  # Buch ist nicht verfügbar

library.return_book("1984")
library.show_available_books()
library.show_books_by_author("George Orwell")

Buch verfügbar: 1984 von George Orwell
Buch verfügbar: Animal Farm von George Orwell
Buch verfügbar: To Kill a Mockingbird von Harper Lee
Du hast das Buch '1984' ausgeliehen.
Das Buch '1984' wurde zurückgegeben.
Verfügbare Bücher:
- 1984
- Animal Farm
- To Kill a Mockingbird
Bücher von George Orwell:
- 1984
- Animal Farm
