Im folgenden sind drei Aufgaben gegeben, eventuell ähnlich zu was im Kurztest zu erwarten wäre:

## Aufgabe 1: Array Indizierung
Generiere ein 1D-Numpy-Array mit 1000 zufälligen Ganzzahlen. Die Aufgabe besteht darin, den 23. kleinsten Wert im Array zu finden und seinen Index zurückzugeben. Verwende dazu geeignete Numpy-Methoden.

In [20]:
import numpy as np

arr = np.random.randint(1, 1001, size=1000) # generiert zufälliges 1D numpy array mit 1000 integers

sorted_indices = np.argsort(arr) # sortiere Indizes
value_23rd_smallest = arr[sorted_indices[22]] # 23. kleinster Wert 

index_23rd_smallest = np.where(arr == value_23rd_smallest)[0][0] # 1. [0] extrahiert Array von Indizes aus dem von np.where zurückgegebenen Tupel; 2. [0] gibt den ersten Index des Arrays

print("23rd Smallest Value:", value_23rd_smallest)
print("Index of 23rd Smallest Value:", index_23rd_smallest)

23rd Smallest Value: 28
Index of 23rd Smallest Value: 793


## Aufgabe 2: Matrixoperationen
Erstelle eine 2D-Numpy-Array-Matrix, in der jede Zeile einem Student entspricht und jede Spalte soll die Ergebnisse dieser Stundenten in einer Reihe benoteter Übungen angeben. Es seien 10 Stundenten mit 5 benoteten Übungen.

a) Identifiziere den Student, dessen Durchschnittspunktzahl dem Gesamtmittelwert aller Studenten am nächsten kommt.

b) Identifiziere den Student, der zwischen seinem ersten und seinem letzten Ergebnis die größte Verbesserung erzielt hat.

In [44]:
import numpy as np

mat = np.random.randint(0, 101, size=(10,5)) # erstellt zufällige Matrix mit möglichen Ergebnissen

# a)
row_means = mat.mean(axis=1) # Durchschnittsnoten pro student
overall_mean = mat.mean() # allgemeine Durchschnitt
closest_to_mean_index = np.argmin(np.abs(row_means - overall_mean))

# b) last score - first score
improvements = mat[:, -1] - mat[:, 0]  # Verbesserungen aller Studenten
greatest_improvement_index = np.argmax(improvements)

print("Scores Matrix:\n", mat)
print(f"Student closest to the mean is at index: {closest_to_mean_index}, Avg Score: {row_means[closest_to_mean_index]:.2f}")
print(f"Student with greatest improvement is at index: {greatest_improvement_index}, Improvement: {improvements[greatest_improvement_index]}")

Scores Matrix:
 [[ 23  32  73  61  15]
 [ 71  39  33  65  87]
 [ 65  44  72  34  55]
 [ 69  28  38  69  40]
 [ 89  28  74  53  80]
 [ 59  54  65  43   2]
 [ 17  26  16 100  81]
 [ 31  67  98 100   5]
 [ 46  44   8  48  63]
 [ 66  16  73  26  83]]
Student closest to the mean is at index: 9, Avg Score: 52.80
Student with greatest improvement is at index: 6, Improvement: 64


## Aufgabe 3: Klassenerstellung und Aufruf von Methoden in der Klasse
Erstelle eine Python Klasse "Student", welche Folgendes kann:

a) Initialisiere einen Student mit einem Namen und einer List von seinen Testresultaten.

b) Berechne die durchschnittliche Punktzahl des Students und geben diese mit der Methode "calculate_average“ zurück.

c) Erstelle ein Studentenobjekt, den Student Peter. Die Methode vom Objekt aufgerufen werden und den Durchschnitt von Peter ausgeben.
Peters Ergebnisse sind [85, 80, 78, 92, 95]. 

d) Gebe zusätzlich an, wenn der Student insgesamt 250 Punkte oder mehr erricht, dass er bestanden hat.

In [49]:
# a)
class Student: # erstellt Klasse Student
    def __init__(self, name, scores): # initialisiert Klasse
        self.name = name
        self.scores = scores
# b)
    def calculate_average(self): # erstellt Funktion
        return sum(self.scores) / len(self.scores)
# c)
student = Student("Peter", [85, 80, 78, 92, 95]) # erstellt Beispiel Studentobjekt mit Attributen

average_score = student.calculate_average() # Durchschnitt des Students
print(f"Student Name: {student.name}")
print(f"Average Score: {average_score:.2f}")

# d)
ergebnisse = [85, 80, 78, 92, 95]
gesamtpunktzahl = sum(ergebnisse)

if gesamtpunktzahl >= 250: 
    print("Peter hat bestanden.")
else:
    print("Peter hat nicht bestanden.")

Student Name: Peter
Average Score: 86.00
Peter hat bestanden.
