# KT5 Preparation
- pop lists
- argmax & argsort
- list in list
- e.g.: x & y gegeben: über y wurde etwas berechnet: erstelle eine Liste mit den 10 größten Varianzwerten
-> bzw. allgemein höchste Elementwerte wiedergeben (vor / nach pop list)

In [6]:
# pop lists
my_list = [1, 2, 3, 4, 5]
popped_element = my_list.pop() # without any argument, last element is popped
print(popped_element)
print(my_list)

popped_element = my_list.pop(0) # with index, element at that index is popped
print(popped_element)
print(my_list)

5
[1, 2, 3, 4]
1
[2, 3, 4]


In [7]:
# argmax & argsort
import numpy as np
arr = np.array([3, 1, 2, 5, 4])
index_of_max = np.argmax(arr) # analog für argmin
print(index_of_max)

sorted_indices = np.argsort(arr)
print(sorted_indices)

# sorted numbers
sorted_array = arr[sorted_indices]
print(sorted_array)

3
[1 2 0 4 3]
[1 2 3 4 5]


In [8]:
# list in list
nested_list = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

# accessing elements
first_sublist = nested_list[0]
print(first_sublist)

second_element_of_second_sublist = nested_list[1][1]
print(second_element_of_second_sublist)

[1, 2, 3]
5


In [9]:
# Create a list with the 10 largest variance values
import numpy as np
arr = np.random.randint(0, 100, size=(100, 100)) # 2D array with 100x100 columns
print(arr)

# Calculate the variance of each row in the original 2D array
variances = np.var(arr, axis=1)

# Get the indices of the 10 largest variances
largest_variance_indices = np.argsort(variances)[-10:]

# Create a list with the 10 largest variance values
largest_variances = variances[largest_variance_indices]
print(largest_variances)

[[18 39 58 ... 53 31 41]
 [68  8  0 ... 90 95 36]
 [16 45 59 ...  9  5 54]
 ...
 [83 89  5 ... 53 52 94]
 [58 20 81 ... 97 92 27]
 [65 18 16 ... 96 31 35]]
[907.64   908.3675 910.8316 913.2731 914.8944 918.3051 931.12   933.7531
 955.6964 955.9884]


In [10]:
import numpy as np

x = np.random.randint(100)
y = np.random.randint(0, 100, size=(100, 100))  # Assuming y is a 2D 100x100 array

# Calculate variance for each column in y
variances = np.var(y, axis=0)

# Get indices of the 10 largest variances
largest_variance_indices = np.argsort(variances)[-10:]

# Create a list with the 10 largest variance values
largest_variances = variances[largest_variance_indices]
print(largest_variances)

[ 919.4875  936.1699  937.7044  946.9524  952.5619  976.5971  984.7936
  998.2736 1021.61   1032.0156]
